- hosts: pulsarservers

  handlers:
    - name: restart pulsar
      become: yes
      service:
        name: pulsar
        enabled: yes
        state: restarted

  tasks:
    - name: import keys task
      include_tasks: keys.yml

    - name: import cron tasks
      include_tasks: cron.yml

    - name: import scripts tasks
      include_tasks: scripts.yml

    - name: import metrics tasks
      include_tasks: metrics.yml

    - name: Create container image cache path
      file:
        path: "{{ pulsar_container_image_cache_path }}"
        state: directory
        mode: '0775'

    - name: Copy Pulsar application configuration file
      template:
        src: "{{ inventory_hostname }}/app.yml.j2"
        dest: "{{ pulsar_root_path }}/config/app.yml"
        force: yes
      notify: restart pulsar

    - name: Apply patch to multiple files under basedir
      patch:
        src: "{{ item.src }}"
        basedir: "{{ item.basedir }}"
        strip: 1
        state: "{{ item.state }}"
        backup: "{{ item.backup }}"
      loop: "{{ patches_to_apply }}"
      when: apply_patches | bool
      notify: restart pulsar
